#!/bin/bash

# Nirit Desktop Environment Startup File

xrandr --output Virtual1 --primary --mode 1920x1080
udiskie -t &
cbatticon &
ibus start &
connman-gtk &
pasystray &
dunst &
feh --bg-scale ~/.config/nirit/wallpaper.jpg &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
qtile start
